name: "laravel-pint-action"
description: "Simple laravel-pint action"
inputs:
  args:
    description: "laravel-pint args"
    required: true
  auto_commit:
    description: "auto commit formatted code and add the current commit to .git-blame-ignore-revs"
    required: false
    default: false
  pr_comment:
    description: "create pr comment with pint output"
    required: false
    default: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
    - ${{ inputs.auto_commit }}
    - ${{ inputs.pr_comment }}
